#!/usr/bin/env python3
"""Render THIRD-PARTY-NOTICES.md and src/lib/notices.generated.ts.

Input is `cargo about generate --format json` output plus the hand-maintained
header at scripts/notices-header.md. Driven by scripts/gen-notices.sh.

Fails (exit 2) if any dependency carries a GPL/LGPL/AGPL license, which would
block a paid release. about.toml's `accepted` list is the primary gate; this is
a second, independent check on the resolved graph.
"""

from __future__ import annotations

import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

# Crates that are ours. They are workspace members, so cargo-about lists them
# alongside real dependencies; `private.ignore` only covers `publish = false`.
FIRST_PARTY = {
    "atv-optimizer-mobile",
    "atvopt-license",
    "shield-optimizer-core",
    "shield-optimizer-v2",
    "tauri-plugin-atv-adb",
}

COPYLEFT = re.compile(r"\b(AGPL|LGPL|GPL)\b", re.IGNORECASE)


def main() -> int:
    if len(sys.argv) != 6:
        print(
            "usage: render-notices.py <about.json> <header.md> <version> "
            "<out.md> <out.ts>",
            file=sys.stderr,
        )
        return 64

    about_path, header_path, version, out_md, out_ts = sys.argv[1:]
    about = json.loads(Path(about_path).read_text())
    header = Path(header_path).read_text()

    crates = [
        c
        for c in about["crates"]
        if c["package"]["name"] not in FIRST_PARTY
    ]
    crates.sort(key=lambda c: (c["package"]["name"].lower(), c["package"]["version"]))

    flagged = [
        f"{c['package']['name']} {c['package']['version']} ({c['license']})"
        for c in crates
        if c["license"] and COPYLEFT.search(c["license"])
    ]
    if flagged:
        print("GPL-family license detected — this blocks a paid release:", file=sys.stderr)
        for f in flagged:
            print(f"  {f}", file=sys.stderr)
        return 2

    # Strip the header comment block; it is guidance for maintainers, not notice text.
    body = [re.sub(r"^<!--.*?-->\n", "", header, count=1, flags=re.DOTALL).rstrip()]

    body.append("\n## Rust crate dependencies\n")
    body.append(
        f"{len(crates)} crates are linked into the Android build "
        "(build-time and dev-only crates excluded).\n"
    )
    body.append("| License | Crates |")
    body.append("| --- | --- |")
    counts = Counter()
    for c in crates:
        for ident in sorted(set(re.findall(r"[A-Za-z0-9.\-+]+", c["license"] or ""))):
            if ident in {"OR", "AND", "WITH"}:
                continue
            counts[ident] += 1
    for ident, count in sorted(counts.items(), key=lambda kv: (-kv[1], kv[0])):
        body.append(f"| {ident} | {count} |")
    body.append(
        "\nA crate under `A OR B` is counted under both; we distribute under whichever term "
        "applies, and the texts below cover every option offered.\n"
    )

    body.append("| Crate | Version | License |")
    body.append("| --- | --- | --- |")
    for c in crates:
        pkg = c["package"]
        repo = (pkg.get("repository") or "").strip()
        name = f"[{pkg['name']}]({repo})" if repo.startswith("http") else pkg["name"]
        body.append(f"| {name} | {pkg['version']} | {c['license'] or 'unknown'} |")

    # Group license texts by SPDX id, deduplicating byte-identical texts (many
    # crates ship the same MIT text) while keeping distinct copyright notices.
    by_id: dict[str, dict[str, set[str]]] = defaultdict(lambda: defaultdict(set))
    for entry in about["licenses"]:
        text = entry["text"].strip("\n")
        for user in entry["used_by"]:
            crate = user["crate"]["name"]
            if crate in FIRST_PARTY:
                continue
            by_id[entry["id"]][text].add(f"{crate} {user['crate']['version']}")

    body.append("\n## License texts\n")
    for license_id in sorted(by_id):
        body.append(f"### {license_id}\n")
        for text in sorted(by_id[license_id], key=lambda t: (-len(t), t)):
            users = sorted(by_id[license_id][text], key=str.lower)
            body.append(f"Used by: {', '.join(users)}\n")
            body.append("```")
            body.append(text.replace("```", "'''"))
            body.append("```\n")

    markdown = "\n".join(body).rstrip() + "\n"
    generated = (
        f"<!-- Generated by mobile/scripts/gen-notices.sh for version {version}. "
        "Do not edit. -->\n"
    )
    markdown = generated + markdown

    Path(out_md).write_text(markdown)

    ts = (
        "// Generated by mobile/scripts/gen-notices.sh. Do not edit.\n"
        "// Mirrors mobile/THIRD-PARTY-NOTICES.md so the app can show notices offline.\n"
        "// Large (hundreds of KB) — import it dynamically so it lands in its own chunk.\n"
        f"export const THIRD_PARTY_NOTICES_VERSION = {json.dumps(version)};\n\n"
        f"export const THIRD_PARTY_NOTICES: string = {json.dumps(markdown)};\n"
    )
    Path(out_ts).write_text(ts)

    print(f"  crates inventoried: {len(crates)}")
    print(f"  licenses: {', '.join(f'{k}={v}' for k, v in sorted(counts.items()))}")
    print(f"  {out_md}: {len(markdown):,} bytes")
    print(f"  {out_ts}: {len(ts):,} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
